### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by kuangshp** [Teeoo/Firstsight#1]
`js
public async addArticle(
    @Args('newArticleInput') data: NewArticleInput,
    @AuthUser() user: User,
  ): Promise<Article> {
    const result = await this.articleService.create(data, user);
    await pubSub.publish('NEWARTICLE', {
      onArticle: this.articleService.findAll(),
    });
    return result;
  }
`
我看到`@AuthUser() user: User,`取用户,但是我看登录的时候没存的方法呢，不知道怎么就存进去了

**Comment by Teeoo** [comment]
> `js public async addArticle( @Args('newArticleInput') data: NewArticleInput, @AuthUser() user: User, ): Promise<Article> { const result = await this.articleService.create(data, user); await pubSub.publish('NEWARTICLE', { onArticle: this.articleService.findAll(), }); return result; } `
> 我看到`@AuthUser() user: User,`取用户,但是我看登录的时候没存的方法呢，不知道怎么就存进去了

```typescript
   // /src/back/auth/auth.strategy.ts

    /**
     * validate 方法实现了父类的抽象方法，在解密授权令牌成功后，即本次请求的授权令牌是没有过期的，
     * 此时会将解密后的 payload 作为参数传递给 validate 方法，这个方法需要做具体的授权逻辑，比如这里我使用了通过用户名查找用户是否存在。
     * 当用户不存在时，说明令牌有误，可能是被伪造了，此时需抛出 UnauthorizedException 未授权异常。
     * 当用户存在时，会将 user 对象添加到 req 中，在之后的 req 对象中，可以使用 req.user 获取当前登录用户。
     */
    async validate(payload: { account: string }) {
        const user = await this.authService.validateUser(payload);
        if (!user) {
            throw new UnauthorizedException();
        }
        return user;
    }
```
